option(GECND_USE_GL_EGL "Use EGL window backend" OFF)
option(GECND_USE_GL_GLFW "Use GLFW window backend" ON)
option(GECND_USE_GL_WAYLAND "Use Wayland window backend" OFF)

set(GLAD_DOWNLOAD "https://github.com/gly-engine/archive/archive/refs/heads/glad.tar.gz")
set(GLAD_DIR "${CMAKE_SOURCE_DIR}/vendor/opengl/glad")

set(WAYLAND_VERSION "1.23.1")
set(WAYLAND_REPO "https://github.com/wayland-mirror/wayland")
set(WAYLAND_DIR "${CMAKE_SOURCE_DIR}/vendor/opengl/wayland")

set(GLFW_VERSION "3.4")
set(GLFW_DIR "${CMAKE_SOURCE_DIR}/vendor/opengl/glfw")
set(GLFW_BUILD_WAYLAND OFF CACHE BOOL "" FORCE)
set(GLFW_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(GLFW_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(GLFW_BUILD_DOCS OFF CACHE BOOL "" FORCE)
set(GLFW_INSTALL OFF CACHE BOOL "" FORCE)
set(GLFW_BUILD_X11 ON CACHE BOOL "" FORCE)

set(X11_VERSION "1.8.4")
set(X11_DOWNLOAD "https://github.com/mirror/libX11/archive/refs/tags/libX11-${X11_VERSION}.tar.gz")
set(X11_DIR "${CMAKE_SOURCE_DIR}/vendor/opengl/x11")
set(X11_X11_INCLUDE_PATH "${X11_DIR}/include")
set(X11_X11_LIB "${X11_DIR}/lib/libX11.so")
set(XPROTO_VERSION "2025.1")
set(XPROTO_DOWNLOAD "https://gitlab.freedesktop.org/xorg/proto/xorgproto/-/archive/xorgproto-${XPROTO_VERSION}/xorgproto-xorgproto-${XPROTO_VERSION}.tar.gz")
set(XPROTO_DIR "${CMAKE_SOURCE_DIR}/vendor/opengl/xorgproto")
set(XRANDR_VERSION "1.5.5")
set(XRANDR_DOWNLOAD "https://gitlab.freedesktop.org/xorg/lib/libxrandr/-/archive/libXrandr-${XRANDR_VERSION}/libxrandr-libXrandr-${XRANDR_VERSION}.tar.gz")
set(XRANDR_DIR "${CMAKE_SOURCE_DIR}/vendor/opengl/xrandr")
set(XINERAMA_VERSION "1.1.4")
set(XINERAMA_DOWNLOAD "https://gitlab.freedesktop.org/xorg/lib/libxinerama/-/archive/libXinerama-${XINERAMA_VERSION}/libxinerama-libXinerama-${XINERAMA_VERSION}.tar.gz")
set(XINERAMA_DIR "${CMAKE_SOURCE_DIR}/vendor/opengl/xinerama")
set(XKB_VERSION "1.0.9")
set(XKB_DOWNLOAD "https://gitlab.freedesktop.org/xorg/lib/libxkbfile/-/archive/libxkbfile-${XKB_VERSION}/libxkbfile-libxkbfile-${XKB_VERSION}.tar.gz")
set(XKB_DIR "${CMAKE_SOURCE_DIR}/vendor/opengl/xkbfile")
set(XCURSOR_VERSION "1.1.12")
set(XCURSOR_DOWNLOAD "https://gitlab.freedesktop.org/xorg/lib/libxcursor/-/archive/libXcursor-${XCURSOR_VERSION}/libxcursor-libXcursor-${XCURSOR_VERSION}.tar.gz")
set(XCURSOR_DIR "${CMAKE_SOURCE_DIR}/vendor/opengl/xcursor")
set(XI_VERSION "1.8.2")
set(XI_DOWNLOAD "https://gitlab.freedesktop.org/xorg/lib/libxi/-/archive/libXi-${XI_VERSION}/libxi-libXi-${XI_VERSION}.tar.gz")
set(XI_DIR "${CMAKE_SOURCE_DIR}/vendor/opengl/xi")
set(XEXT_VERSION "1.2.0")
set(XEXT_DOWNLOAD "https://gitlab.freedesktop.org/xorg/lib/libXext/-/archive/libXext-${XEXT_VERSION}/libxext-libXext-${XEXT_VERSION}.tar.gz")
set(XEXT_DIR "${CMAKE_SOURCE_DIR}/vendor/opengl/xext")
set(XRENDER_VERSION "0.9.10")
set(XRENDER_DOWNLOAD "https://gitlab.freedesktop.org/xorg/lib/libXrender/-/archive/libXrender-${XRENDER_VERSION}/libxrender-libXrender-${XRENDER_VERSION}.tar.gz")
set(XRENDER_DIR "${CMAKE_SOURCE_DIR}/vendor/opengl/xrender")
set(XFIXES_VERSION "6.0.0")
set(XFIXES_DOWNLOAD "https://gitlab.freedesktop.org/xorg/lib/libxfixes/-/archive/libXfixes-${XFIXES_VERSION}/libxfixes-libXfixes-${XFIXES_VERSION}.tar.gz")
set(XFIXES_DIR "${CMAKE_SOURCE_DIR}/vendor/opengl/xfixes")
set(X11_Xrandr_INCLUDE_PATH "${XRANDR_DIR}/include")
set(X11_Xinerama_INCLUDE_PATH "${XINERAMA_DIR}/include")
set(X11_Xkb_INCLUDE_PATH "${XKB_DIR}/include")
set(X11_Xcursor_INCLUDE_PATH "${XCURSOR_DIR}/include")
set(X11_Xi_INCLUDE_PATH "${XI_DIR}/include")
set(X11_Xshape_INCLUDE_PATH "${XEXT_DIR}/include")
set(X11_Xrender_INCLUDE_PATH "${XRENDER_DIR}/include")
set(X11_Xfixes_INCLUDE_PATH "${XFIXES_DIR}/include")
set(X11_HEADERS "${X11_DIR}/include;${XPROTO_DIR}/include")
set(X11_HEADERS_EXTRA "${X11_Xinerama_INCLUDE_PATH};${X11_Xinerama_INCLUDE_PATH};${X11_Xkb_INCLUDE_PATH};${X11_Xcursor_INCLUDE_PATH};${X11_Xi_INCLUDE_PATH};${X11_Xshape_INCLUDE_PATH};${X11_Xrender_INCLUDE_PATH};${X11_Xfixes_INCLUDE_PATH}")

if(GECND_USE_GL_EGL OR GECND_USE_GL_GLFW OR GECND_USE_GL_WAYLAND)
    if (NOT EXISTS "${GLAD_DIR}/include")
        FetchContent_Populate(glad URL ${GLAD_DOWNLOAD} SOURCE_DIR ${GLAD_DIR})
    endif()
    add_library(glad_gl STATIC "${GLAD_DIR}/src/gl.c")
    target_include_directories(glad_gl SYSTEM PRIVATE "${GLAD_DIR}/include")
    target_link_libraries(${PROJECT_NAME} PRIVATE glad_gl)

    file(GLOB_RECURSE gecnd_bakend_files
        "${CMAKE_CURRENT_LIST_DIR}/../lib/Backend_OpenGL/pipeline/*.c"
        "${CMAKE_CURRENT_LIST_DIR}/../lib/Backend_OpenGL/render/*.c"
        "${CMAKE_CURRENT_LIST_DIR}/../lib/Backend_OpenGL/window/common.c"
    )

    if(GECND_USE_GL_GLFW)
        if (NOT EXISTS "${X11_DIR}/include")
            FetchContent_Populate(x11 URL ${X11_DOWNLOAD} SOURCE_DIR ${X11_DIR})
        endif()
        if (NOT EXISTS "${XPROTO_DIR}/include")
            FetchContent_Populate(xproto URL ${XPROTO_DOWNLOAD} SOURCE_DIR ${XPROTO_DIR})
        endif()
        if (NOT EXISTS "${XRANDR_DIR}/include")
            FetchContent_Populate(xrandr URL ${XRANDR_DOWNLOAD} SOURCE_DIR ${XRANDR_DIR})
        endif()
        if (NOT EXISTS "${XINERAMA_DIR}/include")
            FetchContent_Populate(xinerama URL ${XINERAMA_DOWNLOAD} SOURCE_DIR ${XINERAMA_DIR})
        endif()
        if (NOT EXISTS "${XKB_DIR}/include")
            FetchContent_Populate(xkbfile URL ${XKB_DOWNLOAD} SOURCE_DIR ${XKB_DIR})
        endif()
        if (NOT EXISTS "${XCURSOR_DIR}/include")
            FetchContent_Populate(xcursor URL ${XCURSOR_DOWNLOAD} SOURCE_DIR ${XCURSOR_DIR})
        endif()
        if (NOT EXISTS "${XI_DIR}/include")
            FetchContent_Populate(xi URL ${XI_DOWNLOAD} SOURCE_DIR ${XI_DIR})
        endif()
        if (NOT EXISTS "${XEXT_DIR}/include")
            FetchContent_Populate(xext URL ${XEXT_DOWNLOAD} SOURCE_DIR ${XEXT_DIR})
        endif()
        if (NOT EXISTS "${XRENDER_DIR}/include")
            FetchContent_Populate(xext URL ${XRENDER_DOWNLOAD} SOURCE_DIR ${XRENDER_DIR})
        endif()
        if (NOT EXISTS "${XFIXES_DIR}/include")
            FetchContent_Populate(xext URL ${XFIXES_DOWNLOAD} SOURCE_DIR ${XFIXES_DIR})
        endif()
        FetchContent_Declare(
            glfw
            GIT_REPOSITORY https://github.com/glfw/glfw
            GIT_TAG ${GLFW_VERSION}
            SOURCE_DIR ${GLFW_DIR}
        )
        FetchContent_MakeAvailable(glfw)
        target_link_libraries(${PROJECT_NAME} PRIVATE glfw)
        target_include_directories(glfw SYSTEM PRIVATE "${X11_HEADERS};${X11_HEADERS_EXTRA}")
        set_source_files_properties("${CMAKE_CURRENT_LIST_DIR}/../lib/Daemon_Inputs/service_keymap.c"
            PROPERTIES COMPILE_DEFINITIONS "GLFW_DEFAULT_INPUT_CLASS=\"void://glfw\""
        )
        list(APPEND gecnd_bakend_files "${CMAKE_CURRENT_LIST_DIR}/../lib/Backend_OpenGL/window/glfw.c")
    endif()

    if(GECND_USE_GL_EGL OR GECND_USE_GL_WAYLAND)
        add_library(glad_egl STATIC "${GLAD_DIR}/src/egl.c")
        target_include_directories(glad_egl SYSTEM PRIVATE "${GLAD_DIR}/include")
        target_link_libraries(${PROJECT_NAME} PRIVATE glad_egl)
        if (GECND_USE_GL_EGL)
            list(APPEND gecnd_bakend_files "${CMAKE_CURRENT_LIST_DIR}/../lib/Backend_OpenGL/window/egl.c")
        endif()
        if(GECND_USE_GL_WAYLAND)
            if (NOT EXISTS "${WAYLAND_DIR}/src")
                FetchContent_Populate(wayland GIT_REPOSITORY ${WAYLAND_REPO} GIT_TAG ${WAYLAND_VERSION} SOURCE_DIR ${WAYLAND_DIR})
            endif()
            list(APPEND gecnd_bakend_files "${CMAKE_CURRENT_LIST_DIR}/../lib/Backend_OpenGL/window/wayland.c")
        endif()
    endif()

    file(GLOB_RECURSE GLSL_SOURCES "${CMAKE_CURRENT_LIST_DIR}/../lib/Backend_OpenGL/shadder/*")
    foreach(GLSL ${GLSL_SOURCES})
        string(REGEX REPLACE "^.*Backend_OpenGL/?" "" GLSL_SHORT "${GLSL}")
        string(REGEX REPLACE "[./]" "_" GLSL_NAME "${GLSL_SHORT}")
        set(GLSL_OUT ${CMAKE_BINARY_DIR}/include/gecnd/${GLSL_NAME}.h)
        add_custom_command(
            OUTPUT ${GLSL_OUT}
            COMMAND xxd -i ${GLSL_SHORT} > ${GLSL_OUT}
            DEPENDS ${GLSL}
            COMMENT "Generating header ${GLSL_OUT}"
            WORKING_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}/../lib/Backend_OpenGL"
        )
        list(APPEND GENERATED_HEADERS ${GLSL_OUT})
    endforeach()

    add_custom_target(gecnd_glsl_headers DEPENDS ${GENERATED_HEADERS})
    add_dependencies(${PROJECT_NAME} gecnd_glsl_headers)
    set_source_files_properties(${gecnd_bakend_files} PROPERTIES INCLUDE_DIRECTORIES "${GLAD_DIR}/include;${GLFW_DIR}/include")
    if(GECND_USE_GL_WAYLAND)
        set_source_files_properties("${CMAKE_CURRENT_LIST_DIR}/../lib/Backend_OpenGL/window/wayland.c"
            PROPERTIES INCLUDE_DIRECTORIES "${GLAD_DIR}/include;${WAYLAND_DIR}/src;${WAYLAND_DIR}/egl"
        )
    endif()
    target_sources(${PROJECT_NAME} PRIVATE "${gecnd_bakend_files}")
    target_link_libraries(${PROJECT_NAME} PRIVATE ${CMAKE_DL_LIBS})
endif()
